[package]
name = "luajit-ripper"
version = "0.1.6"
description = "A LuaJIT bytecode decompiler"
license = "GPL-3.0-only"
documentation = "https://docs.rs/luajit-ripper"
repository = "https://github.com/balthild/luajit-ripper"
edition = "2024"

[features]
default = []
cli = ["dep:clap", "dep:rayon", "dep:walkdir"]

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
oxc_allocator = "0.150.0"
rayon = { version = "1", optional = true }
thiserror = "2"
walkdir = { version = "2", optional = true }

[lib]
name = "luajit_ripper"
path = "src/lib.rs"

[[bin]]
name = "luajit-ripper"
path = "src/main.rs"
required-features = ["cli"]

[[test]]
name = "cli"
path = "tests/cli.rs"
required-features = ["cli"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.release]
pre-release-commit-message = "chore: release {{crate_name}} version {{version}}"
tag-message = "chore: release {{crate_name}} version {{version}}"
